### ISSUE TITLE
Why iOS 8.2?

### ISSUE THREAD

**Issue by hdoria** [icanzilb/SwiftSpinner#10]
Swift 1.2 is compatible with iOS 7+.

**Comment by jschmid** [comment]
+1 :disappointed:

**Comment by jschmid** [comment]
For the record, I use (for now)

    pod 'SwiftSpinner', '=0.6.1'

**Comment by icanzilb** [comment]
well, Xcode 6.3 requires 8.2 or higher to use the library as a cocoapod (or so I understand from the error message) 

![image](https://cloud.githubusercontent.com/assets/633862/7083587/1a2e4c5a-df64-11e4-94a4-112ba148851e.png)

If you just add SwiftSpinner.swift to your project you can use it with earlier versions.

**Comment by icanzilb** [comment]
if any of you guys discover a workaround for this - let me know - I also think 8.2+ is too extreme provided the latest one is 8.3 ...

**Comment by jschmid** [comment]
I don't know where you got this error from, because I just ran the example project and it works perfectly.

I updated the podspec with `s.platform     = :ios, '8.0'`, ran `pod install` in the DemoApp folder.

Xcode 6.3 is required to **build** Swift 1.2 sources, but it can run on 7.0. Note that Cocoapod requires 8.0 because of some compilation things I did not try to understand.

**Comment by icanzilb** [comment]
the example project has already a minimum build target of 8.2 that's why there's no error.

Try setting the deployment target to:

![image](https://cloud.githubusercontent.com/assets/633862/7084509/4091dec0-df6e-11e4-856d-2a0b5cb1ecfa.png)

And then build again and you will see the error

**Comment by jschmid** [comment]
I forgot to say it in my comment, but I also updated to Target to 8.0. It worked. :|

**Comment by icanzilb** [comment]
can you zip the project, upload it, and paste a link here? I'm really curious what's going on here

**Comment by jschmid** [comment]
See this: [removed link]

**Comment by icanzilb** [comment]
crazy ... your project **does** work! there must be something wrong either with my xcode or with my head, lol ... either way I'll figure it out, thanks for helping!

**Comment by jschmid** [comment]
I suggest that you publish a new Pod version with 8.0 requirements. Then you'll be able to make a test with a fresh project :)

**Comment by icanzilb** [comment]
actually the demo app uses the pod locally, I'll fix everything here and then push online

**Comment by icanzilb** [comment]
i can't believe it. somehow (it was totally not me) the target of the pod got min deployment target of 8.2 and that's why the error was showing for me ... removed project pods, then installed again and there you go ... the cocoa pod 0.6.6 is pushed up should appear in few moments

**Comment by jschmid** [comment]
Much better :+1:

**Comment by hdoria** [comment]
Great work. Thanks. :)
