### ISSUE TITLE
Can't use with app extension

### ISSUE THREAD

**Issue by shshlomi** [icanzilb/SwiftSpinner#109]
Hi,

I tried to use it in a keyboard app extension and it doesn't work.
The reason is that app extension is not allowed to use UIApplication.shared.
Is it possible to fix it?

Thanks

**Comment by psk239** [comment]
I just submitted a [PR for this issue](https://github.com/icanzilb/SwiftSpinner/pull/111)

**Comment by shshlomi** [comment]
Great, Thank you.

**Comment by icanzilb** [comment]
This should be fixed by @psk239 's PR: https://github.com/icanzilb/SwiftSpinner/releases/tag/1.3.0
