### ISSUE TITLE
SwiftSpinner.show(duration: 2.0, ...) cannot be canceled

### ISSUE THREAD

**Issue by danielpluvia** [icanzilb/SwiftSpinner#114]
Hi,

I found that `SwiftSpinner.show(duration: 2.0, title: "Connected", animated: false)` cannot be canceled by `SwiftSpinner.show("Connected", animated: false)`.

E.g.
`SwiftSpinner.show(duration: 2.0, title: "Connected", animated: false)`
`SwiftSpinner.show("Connecting...")`.

What I want to do is making it shows 'Connecting' all the time. However, it shows "Connected" firstly (it disappears very quickly so we cannot see, that is fine), then it shows "Connecting..." and **it disappears after 2 seconds**.

The reason is that the first function calls `SwiftSpinner.hide()` after 2 seconds and there is no way to cancel it. So whatever I did after I call `show(duration:...)`, it will hide the SwiftSpinner after the duration. Is there any way that I can cancel the duration action after calling it?

Regards,

Daniel

**Comment by aamck** [comment]
Look at the `ViewController.swift` class in the demo app that's included in the repo. It pretty much does exactly what you're trying to achieve.

In your example all you're doing is overwriting the title nothing else.

**Comment by danielpluvia** [comment]
Thanks for the reply. I tried to make the example as simple as possible, but it seems that it leads to a misunderstanding.

Here is what I tried to do:

`SwiftSpinner.show(duration: 6.0, title: "Connecting ...", animated: true)`
// Do something in background to connect
// There is a response whitin 2 seconds
    // If succeed
        `SwiftSpinner.show("Connected")`
    // else If failed
        `SwiftSpinner.show("Failed")

What I want is to show "Connected" or "Failed" in the end. However, here is what really happens:

1. 0s - 2s: It shows "Connecting ...", which is right
2. 2s - 6s: It shows "Connected" or "Failed", which is right as well
3. 6s:        _**SwiftSpinner disappears**_, which is wrong

I think the SwiftSpinner shouldn't disappear because I called `show()` after the `show(duration:...)` function. But there is nothing that I can do to stop it disappearing.

**Comment by aamck** [comment]
You should use a completion handler for your background process to make the appropriate change to the spinner based on what happens.

**Comment by danielpluvia** [comment]
My point is:

`show(duration:...)` function uses `DispatchQueue.main.asyncAfter()` to implement the delay feature, which makes it cannot be cancelled later. Maybe it is better to use a timer instead of using asyncAfter() so that the timer can be cancelled later.

Here is the code that I found in the library:

```
func delay(_ seconds: Double, completion:@escaping ()->()) {
    let popTime = DispatchTime.now() + Double(Int64( Double(NSEC_PER_SEC) * seconds )) / Double(NSEC_PER_SEC)
    
    DispatchQueue.main.asyncAfter(deadline: popTime) {
        completion()
    }
}
```

You can see it is using `DispatchQueue.main.asyncAfter`. Do you think it would help if we use NSTimer here?

**Comment by danielpluvia** [comment]
And here is the code which calls the delay function:
```
public class func show(duration: Double, title: String, animated: Bool = true) -> SwiftSpinner {
    let spinner = SwiftSpinner.show(title, animated: animated)
    spinner.delay(duration) {
        SwiftSpinner.hide()
    }
    return spinner
}
```

If we call a show(duration:) function, there would be no way stopping it from calling `SwiftSpinner.hide()` after the duration. Maybe we can implement a function to give people a chance to let them undo this part
```
spinner.delay(duration) {
        SwiftSpinner.hide()
    }
```
?

**Comment by aamck** [comment]
I don't understand why you'd over complicate it with timers though?

- `SwiftSpinner.show(title: "Connecting ...")`
- Run your networking
- If it succeeds `SwiftSpinner.show(title: "Success")`
- If it fails `SwiftSpinner.show(title: "Fail")`

Using a timer and running your networking / background process provides you with no contingency if your process takes longer than expected which will ultimately break your app.

**Comment by danielpluvia** [comment]
Well, I did that at last. But I still think it is a good idea to let the next function override the previous state. Because all the other functions did that, for example:

> If you call `show(…)` or `hide()` before the delay time has passed - this will clear the call to `show(delay: …)`.

So why can't we use `show(...)` to clear the call to `show(duration:...)`?

**Comment by aamck** [comment]
You could submit a pull request to allow that behaviour. It doesn't really make much sense though as most use cases are showing the spinner while something happens then removing it when that something completes and using a timer for that as I've said above is bad.

**Comment by danielpluvia** [comment]
Yeah, I agree with you that most use cases don't need this feature, thanks for your patience and the responses. Btw, the spinner looks really great  :)
