### ISSUE TITLE
Set inner/outer color back to default

### ISSUE THREAD

**Issue by martheli** [icanzilb/SwiftSpinner#115]
After using the following:

```
SwiftSpinner.sharedInstance.innerColor = UIColor.red
SwiftSpinner.sharedInstance.outerColor = UIColor.red
        
        
SwiftSpinner.show(duration: 1.5, title: error, animated:false)
```
How do I reset the color back to default? Doesn't seem to be any kind of default property.

**Comment by aamck** [comment]
Just create a default state method then call it whenever you want to reset the spinner. That way your spinner's default can be whatever you want.

**Comment by martheli** [comment]
yea but what is "default". Do I just set the inner and outer color to grey? I am not sure what the default colors are.

**Comment by aamck** [comment]
It's all [here](https://github.com/icanzilb/SwiftSpinner/blob/master/SwiftSpinner/SwiftSpinner.swift). Have a read ; )

**Comment by martheli** [comment]
I tried to do this:

```
func showError(error: String) {
        
        SwiftSpinner.sharedInstance.innerColor = UIColor.red
        SwiftSpinner.sharedInstance.outerColor = UIColor.red
        
        
        SwiftSpinner.show(duration: 1.5, title: error, animated:false)
        
        SwiftSpinner.sharedInstance.innerColor = UIColor.white
        SwiftSpinner.sharedInstance.outerColor = UIColor.white
      
    }
```

But it only shows up white, it never displays the red.

**Comment by aamck** [comment]
That function makes it red then immediately makes it white (no time delay) so the red is never seen even though it is set.

**Comment by martheli** [comment]
Does it make it red after the spinner is shown? I want it to show red and then after it is shown, reset the color back to white for the next time.

**Comment by aamck** [comment]
Look at the demo app that's included in the project and study how the spinner is changed over time to show different things.

Everything you've so far asked how to do can be extrapolated from the examples included with the demo.

**Comment by andreamazz** [comment]
This can be closed, thanks @aamck for the support.
