### ISSUE TITLE
Hierarchy mistake when rootController of UIWindow changed

### ISSUE THREAD

**Issue by CoulsonWang** [icanzilb/SwiftSpinner#118]
I found a mistake when use SwiftSpinner:

If I already "show" Spinner once, spinner will be created, and it will be a subview of keyWindow, it's in the front of the view of rootViewController.
But when i change the rootViewController, Spinner will be under the View of rootViewController. When I "show" again, the hierarchy will be mistake.

I think this problem can be solved by doing this:
move the spinner to the top(use "bringSubviewToFront:" method) in "show" method if the "container view" is not "nil"

**Comment by icanzilb** [comment]
If you open a PR I can review and test

**Comment by CoulsonWang** [comment]
Already opened a PR, check it pls, thanks.

Only add one line code. bring spinner to front when update frame.

**Comment by andreamazz** [comment]
Closing, this was fixed in #120 
Feel free to reopen if the issue persists.
