### ISSUE TITLE
Type 'String' has no member 'round'

### ISSUE THREAD

**Issue by teerayuthton** [icanzilb/SwiftSpinner#128]
XCode 10.0(10A255)
Deployment Target 9.3
cocoapods 1.5.3
SwiftSpinner (1.6.2)

How to fix this issue ?

<img width="1268" alt="screen shot 2561-09-22 at 21 44 02" src="https://user-images.githubusercontent.com/12950654/45918403-bed5bc00-beb0-11e8-9ddb-b086cd34b100.png">
<img width="1269" alt="screen shot 2561-09-22 at 21 44 28" src="https://user-images.githubusercontent.com/12950654/45918411-c5643380-beb0-11e8-8f61-4b12396b06c6.png">
<img width="1268" alt="screen shot 2561-09-22 at 21 44 39" src="https://user-images.githubusercontent.com/12950654/45918412-ca28e780-beb0-11e8-9e43-4ce02b4cc80d.png">

**Comment by icanzilb** [comment]
@andreamazz ?

**Comment by raulastu** [comment]
same issue

**Comment by andreamazz** [comment]
Is the swift version of the pod’s target set to 4.2?

**Comment by teerayuthton** [comment]
> Is the swift version of the pod’s target set to 4.2?

Yes

**Comment by andreamazz** [comment]
I just tried on a fresh project, it compiles fine. It might be a configuration issue somewhere in your project, because if you get these errors, Xcode is probably trying to compile against swift 4 instead of 4.2.
Try to clean the project, and maybe even nuke the workspace and recreate it with `pod install`

**Comment by icanzilb** [comment]
That doesn't seem like a Swift version issue to me. The property changed its value type in iOS12, I'll have a look

**Comment by icanzilb** [comment]
@teerayuthton I also can't reproduce here. Could you please give a try to the demo app in the SwiftSpinner repo and check if it's compiling for you?

**Comment by teerayuthton** [comment]
> @teerayuthton I also can't reproduce here. Could you please give a try to the demo app in the SwiftSpinner repo and check if it's compiling for you?

okay i will try again

**Comment by teerayuthton** [comment]
In your demo project the auto complete display "lineCap" with type CAShapeLayerLineCap

But in my project display String type !!???

<img width="1512" alt="screen shot 2561-09-23 at 22 09 01" src="https://user-images.githubusercontent.com/12950654/45929558-ac758400-bf7d-11e8-9bab-36061665b836.png">

<img width="1712" alt="screen shot 2561-09-23 at 22 08 41" src="https://user-images.githubusercontent.com/12950654/45929561-b5665580-bf7d-11e8-8baa-324640b7c4a4.png">

And i don't know why?

**Comment by icanzilb** [comment]
@teerayuthton okay, in that case it's probably best to try reinstalling your dependencies. What I would do in your place is to delete the Pods folder and the pods lock file as well as the workspace file and then run a fresh `pod install` ...

**Comment by daver234** [comment]
I am having the same issue.  I have not upgraded my project to Swift 4.2.  Is that required to eliminate these errors?  Thanks.

**Comment by daver234** [comment]
I deleted my pods and lock file, did a fresh install.  And clean build.  Same problems.

**Comment by daver234** [comment]
One other clue.  I switched to "Legacy Build System" in my project just recently due to another issue.  In your project, you are new New Build System (File--Project Settings).  Your project on Github builds fine without the errors.  Odd.

**Comment by daver234** [comment]
So I found a solution to this problem. The issue arrises if you update all the PODS in your Workspace before converting your source to Swift 4.2.  I was using Swift 4 with SwiftSpinner 1.5.0.  I updated all my pods before I updated my project source files.  Mistake.  Once I updated all the source files (and not the pods), then deleted all the existing PODS in the project directory, then ran Pod Install, I got things working with SwiftSpinner 1.6.2

**Comment by teerayuthton** [comment]
> So I found a solution to this problem. The issue arrises if you update all the PODS in your Workspace before converting your source to Swift 4.2. I was using Swift 4 with SwiftSpinner 1.5.0. I updated all my pods before I updated my project source files. Mistake. Once I updated all the source files (and not the pods), then deleted all the existing PODS in the project directory, then ran Pod Install, I got things working with SwiftSpinner 1.6.2

Thank!!!!!!! @daver234 your solution it worked!!!!!!

**Comment by goyanimaulik** [comment]
same issue i have
I am using swift 4 that why issue come
In swift 4.2+ its working fine
But i don't want to change swift version of my project.

So i find out below solution. it will working in swift 4
**circleLayer.lineCap = "round"**
