### ISSUE TITLE
after updating pod its showing some errors

### ISSUE THREAD

**Issue by amrit42087** [icanzilb/SwiftSpinner#130]

**Comment by andreamazz** [comment]
Hi @amrit42087 
Care to provide which errors are you getting? Steps to reproduce the issue would be also welcome.

**Comment by DavidLari** [comment]
It works with no errors for me. If you are getting errors, you probably have not updated your main project to Swift 4.2 and it's trying to compile SwiftSpinner with Swift 4. By default, pods will inherit the Swift language version of the main project.
