### ISSUE TITLE
Can't use without crashing after update

### ISSUE THREAD

**Issue by SolorzanoJose** [icanzilb/SwiftSpinner#131]
I updated from 1.0.4 to 1.1.0 and now I get a crash when launching the spinner, I tried all versions up to the latest
```
[SwiftSpinner.SwiftSpinner setUserInteractionEnabled:]: unrecognized selector sent to class 0x10c14c750
2018-11-21 11:33:13.501015-0400 CommonStock[91649:11480586] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[SwiftSpinner.SwiftSpinner setUserInteractionEnabled:]: unrecognized selector sent to class 0x10c14c750'
```

**Comment by SolorzanoJose** [comment]
For context, I'm using XCode 10

**Comment by DavidLari** [comment]
I am using the latest v1.6 on Xcode 10, with Swift language set to 4.2. No problems for me.

Can you provide any more information for us to help see what the problem might be?

**Comment by SolorzanoJose** [comment]
@DavidLari that is great to hear because that means my problem is solvable on my end. I can provide ANY and all information that can help debug the issue, I just have no idea where to look? I have xcode 10, latest version of the pod, swift language set to 4.2 and I can't show the spinner without getting a crash for the unrecognized selector.

Only version that works is 1.0.2 and prior

**Comment by DavidLari** [comment]
Can you show how you're calling it and tell us where it's called from?

**Comment by SolorzanoJose** [comment]
@DavidLari 
``
 @objc func confirmPressed() {
        SwiftSpinner.show("Sending e-mail...")
}
``

This simple code crashes the app, as well as any other call to SwiftSpinner.show that otherwise works well in version 1.0.6

``
Thread 1: EXC_BAD_ACCESS (code=1, address=0x0)
``

**Comment by SolorzanoJose** [comment]
```
SwiftSpinner`SwiftSpinner.SwiftSpinner.addTapHandler(_: () -> (), subtitle: Swift.Optional<Swift.String>) -> ():
    0x107a4a9a4 <+0>:    stp    x20, x19, [sp, #-0x20]!
    0x107a4a9a8 <+4>:    stp    x29, x30, [sp, #0x10]
    0x107a4a9ac <+8>:    add    x29, sp, #0x10            ; =0x10 
    0x107a4a9b0 <+12>:   sub    sp, sp, #0x420            ; =0x420 
    0x107a4a9b4 <+16>:   adrp   x8, 10
    0x107a4a9b8 <+20>:   ldr    x8, [x8, #0x150]
    0x107a4a9bc <+24>:   mov    x9, #0x0
    0x107a4a9c0 <+28>:   stur   x9, [x29, #-0x38]
    0x107a4a9c4 <+32>:   stur   x9, [x29, #-0x50]
    0x107a4a9c8 <+36>:   stur   x0, [x29, #-0x20]
    0x107a4a9cc <+40>:   stur   x1, [x29, #-0x18]
    0x107a4a9d0 <+44>:   stur   x2, [x29, #-0x30]
    0x107a4a9d4 <+48>:   stur   x3, [x29, #-0x28]
    0x107a4a9d8 <+52>:   stur   x20, [x29, #-0x38]
    0x107a4a9dc <+56>:   ldr    x9, [x20]
    0x107a4a9e0 <+60>:   ldr    x8, [x8]
    0x107a4a9e4 <+64>:   and    x8, x9, x8
    0x107a4a9e8 <+68>:   ldr    x8, [x8, #0xf8]
    0x107a4a9ec <+72>:   str    x20, [sp, #0x238]
    0x107a4a9f0 <+76>:   str    x1, [sp, #0x230]
    0x107a4a9f4 <+80>:   str    x0, [sp, #0x228]
    0x107a4a9f8 <+84>:   str    x3, [sp, #0x220]
    0x107a4a9fc <+88>:   str    x2, [sp, #0x218]
    0x107a4aa00 <+92>:   blr    x8
    0x107a4aa04 <+96>:   ldr    x0, [sp, #0x230]
```

**Comment by andreamazz** [comment]
Hey @SolorzanoJose 
I'm trying to reproduce the issue, but I don't think I have all the elements. Just calling the spinner from an action works fine. From the stacktrace that you posted the issue lies in the tap handler, can you show the code you use to add it to the view?

**Comment by andreamazz** [comment]
Marking this as stale, feel free to reopen once you have more details.
