### ISSUE TITLE
SwiftSpinner and status bar

### ISSUE THREAD

**Issue by intacto27** [icanzilb/SwiftSpinner#133]
Hello, is it possible to use SwiftSpinner in application with active statusbar?
now when i add SwiftSpinner to viewcontroller it works fine, but not cover statusbar.

**Comment by andreamazz** [comment]
Hey @intacto27 
You can try to move your window level above the status bar when presenting the spinner:
```swift
UIApplication.shared.keyWindow?.windowLevel = UIWindow.Level.statusBar + 1
```
then set it back to normal:
```swfit
UIApplication.shared.keyWindow?.windowLevel = UIWindow.Level.normal
```

**Comment by andreamazz** [comment]
Closing this. Feel free to reopen if needed.
