### ISSUE TITLE
change swiftSpinner style

### ISSUE THREAD

**Issue by tryadelion** [icanzilb/SwiftSpinner#14]
how can i modify swiftSpinner's style? i'm unable to find find any option to do so. thank you.

**Comment by icanzilb** [comment]
can you rephrase your question? what do you want to achieve?

**Comment by tryadelion** [comment]
modify the colors of the spinner.

**Comment by icanzilb** [comment]
It uses the vibrancy visual effect - I don't think there's any way to make colors
