### ISSUE TITLE
Crash on iOS 16 and Xcode 14

### ISSUE THREAD

**Issue by Taimoor20** [icanzilb/SwiftSpinner#148]
This loader was working fine in iOS 15 but recently I had updated my Xcode 13 to Xcode 14 and iOS 15 to iOS 16 and getting the following crash:

`Thread 52: "Modifications to the layout engine must not be performed from a background thread after it has been accessed from the main thread."` 

I am getting this error in the **Swift Spinner** class on line 171 

> 171. containerView.addSubview(spinner)

Following is the link of the pic of the crash:

[https://ibb.co/fHbGP9z](url)

**Comment by andreamazz** [comment]
Hey @Taimoor20 
I just tested the demo app and everything is working correctly. My best guess is that you are calling `show` from a background thread, you might want to double check your code and eventually wrap that call in a block called on the main thread instead, something like: 
```swift
DispatchQueue.main.async {
  SwiftSpinner.show(delay: 0.5, title: "Hello world", animated: true)
}
```

**Comment by Taimoor20** [comment]
> Hey @Taimoor20 I just tested the demo app and everything is working correctly. My best guess is that you are calling `show` from a background thread, you might want to double check your code and eventually wrap that call in a block called on the main thread instead, something like:
> 
> ```swift
> DispatchQueue.main.async {
>   SwiftSpinner.show(delay: 0.5, title: "Hello world", animated: true)
> }
> ```

Thanks, it works.
