### ISSUE TITLE
Swift Package Manager

### ISSUE THREAD

**Issue by sourov2008** [icanzilb/SwiftSpinner#149]
Please add swift package manager. I converted all of my dependencies into SPM. But I could not remove my Cocoapods due to SwiftSpinner.

**Comment by andreamazz** [comment]
It's already available via SPM:
<img width="833" alt="Screenshot 2024-01-03 at 18 46 06" src="https://github.com/icanzilb/SwiftSpinner/assets/570797/146481e8-ee50-481d-b0ae-471a1e077349">

**Comment by sourov2008** [comment]
Your web link is not working.

Addiotanlay,
Its saying, no package available for this project.

[image: Screenshot 2024-01-03 at 7.37.54 PM.png]


*Sincerely, *

*Shourob DattaEmail : ***@***.*** ***@***.***>   *

**Comment by andreamazz** [comment]
You should be able to see the screen on the GitHub page.
Anyway, I just tried on a fresh project, enter `https://github.com/icanzilb/SwiftSpinner` in the SPM window and you should be able to add it to your packages.
If you're still having issues it might be something misconfigured on your end.

Cheers

**Comment by sourov2008** [comment]
Thanks for your reply. And thanks for your awesome library.



*Sincerely, *

*Shourob DattaEmail : ***@***.*** ***@***.***>   *
