### ISSUE TITLE
SwiftSpinner.hide() not working within function

### ISSUE THREAD

**Issue by redongjika** [icanzilb/SwiftSpinner#15]
Hi,

I am trying to open and hide the SwiftSpinner but it does not work when I isolate the SwiftSpinner.hide() call into a completion block.

The code is : 

```
    SwiftSpinner.show("Connexion...", animated: true)

    loginRequest(loginData, {(success:Bool) -> Void in
        println("value = \(success)")
        SwiftSpinner.hide()
    })
```

The spinner just stops moving without diseappearing. It's like the spinner.removeFromSuperview is not working.
Thank you in advance,

**Comment by icanzilb** [comment]
hmm ... probably your completion block is not executed on the main thread?

**Comment by redongjika** [comment]
That was the reason. Thanks ;)
The new code:

```
    SwiftSpinner.show("Connexion...", animated: true)

    loginRequest(loginData, {(success:Bool) -> Void in
    println("value = \(success)")
    dispatch_async(dispatch_get_main_queue(),{
            SwiftSpinner.hide()
        })
})
```

**Comment by icanzilb** [comment]
it might be interesting to force the hide() code to switch to the main thread automatically ... I'll look into implementing this in the next merge

**Comment by redongjika** [comment]
Good idea ;)
