### ISSUE TITLE
Feature Request: Dismiss on touch

### ISSUE THREAD

**Issue by focusedonfit** [icanzilb/SwiftSpinner#16]
I would love to have the ability to dismiss the spinner when a user touches the screen. This is helpful when displaying error messages to the user.
Thank you

**Comment by icanzilb** [comment]
okay, that sounds like a neat feature - I'll put it on my TODO

**Comment by matthewfcarlson** [comment]
I actually wrote this a few weeks ago along with a few other improvements. If you'd like I could post the source.

**Comment by matthewfcarlson** [comment]
So this is at the end of the init function

```
 //get tap recognizer and set it to close the spinner
        let tap = UITapGestureRecognizer(target:self,action:"spinnerTapped");
        tap.numberOfTapsRequired = 1;
        self.addGestureRecognizer(tap);

    }

    public func spinnerTapped(){
        if (canClose){
            SwiftSpinner.hide();
        }
    }
```

I also added a label that said tap to continue below the spinner. Really some great code, thank you!
