### ISSUE TITLE
Don't adjust when orientation changed

### ISSUE THREAD

**Issue by ziedmahdi** [icanzilb/SwiftSpinner#17]
If we change the device orientation when the spinner is showed, the spinner don't adjust it self for the hole screen. (tested in real iphone 4S device)
![spinner bug](https://cloud.githubusercontent.com/assets/5032634/7790702/232375c8-0288-11e5-9732-adad8c260aba.jpg)

**Comment by icanzilb** [comment]
yeah - that might be a useful feature - I'll look into that

**Comment by ziedmahdi** [comment]
When initializing the spinner, add an orientation handler. if the spinner
is shown just call update and it will adjust itself.

**Comment by icanzilb** [comment]
if you already coded that would mind throwing in some code in a comment on this issue?

**Comment by icanzilb** [comment]
if you already coded that would mind throwing in some code in a comment on this issue?

**Comment by hyouuu** [comment]
Here you go:
In init:
{
...
// Orientation change observer
NSNotificationCenter.defaultCenter().addObserver(
    self,
    selector: "updateOrient",
    name: UIApplicationDidChangeStatusBarOrientationNotification,
    object: nil)
}

public func updateOrient() {
    updateFrame()
  }

**Comment by animaonline** [comment]
Hi, has this issue been fixed? I´m still able to reproduce it. 

@hyouuu your code doesn't seem to work, I suspect the updateFrame needs to be tweaked a bit.

**Comment by icanzilb** [comment]
what are the steps to reproduce the problem on your side? Let me know and I'll give it a try here and fix it if I can reproduce

**Comment by icanzilb** [comment]
@animaonline

**Comment by animaonline** [comment]
Show the spinner, then rotate the device. :)

**Comment by icanzilb** [comment]
this helped a lot - thanks

**Comment by ziedmahdi** [comment]
if you add an observer for device rotation in the SwiftSpinner initializer, it will work as expected only in the simulator. But, for real devices (ex. iPhone 4S), you may add that observer in the AppDelegate class. This is a work around, as the solution should be in the package itself not dependent on other class. Also you have to set updateFrame() method to public in order to call it from outside the SwiftSpinner class.

**Comment by animaonline** [comment]
That's what I did, it didn't help.

On Tuesday, July 14, 2015, ziedmahdi notifications@github.com wrote:

> if you add an observer for device rotation in the SwiftSpinner
> initializer, it will work as expected only in the simulator. But, for real
> devices (ex. iPhone 4S), you may add that observer in the AppDelegate
> class. This is a work around, as the solution should be in the package
> itself not dependent on other class. Also you have to set updateFrame()
> method to public in order to call it from outside the SwiftSpinner class.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/icanzilb/SwiftSpinner/issues/17#issuecomment-121267350
> .

## 

Roman Alifanov - MCAD - MCTS - MCP - MCT
http://www.animaonline.com

**Comment by ziedmahdi** [comment]
this is what worked for me

```
func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
    //adding swift spinner ability to adjust it self for orientation changes
    let notificationCenter = NSNotificationCenter.defaultCenter()
    let mainQueue = NSOperationQueue.mainQueue()

    notificationCenter.addObserverForName(UIDeviceOrientationDidChangeNotification, object: nil, queue: mainQueue) { _ in
        let spinner = SwiftSpinner.sharedInstance
        if spinner.superview != nil {
            spinner.updateFrameOverOrientation()
        }
    }
}
```

you have to add an extension to SwiftSpinner

```
extension SwiftSpinner{
    func updateFrameOverOrientation(){
        self.updateFrame()
    }
}
```

like I said this is a work around, not a good solution because the SwiftSpinner becomes dependent to other class
