### ISSUE TITLE
Custom colors

### ISSUE THREAD

**Issue by tapz** [icanzilb/SwiftSpinner#19]
It would be nice to be able to customize the blur text color. Now the blur color is a private property so subclassing does not help.

**Comment by icanzilb** [comment]
Can you explain in more details which color do you want to customize? If you're talking about the text color - you can't customize it - that's the whole idea of using vibrancy ... if you're thinking about something else let me know what is it?

**Comment by deezaster** [comment]
customizing the blurEffectStyle to .Light would be great. (...in this case the text color should be dark)

**Comment by jeffery812** [comment]
yes, need customized blurEffectStyle to other style, for example .Light

**Comment by icanzilb** [comment]
alright - I made `blurEffect` a public property in `0.9.0` on SwiftSpinner so you could theoretically change the effect yourself with a new `UIBlurEffect` instance

**Comment by icanzilb** [comment]
this is a bit more complicated than I thought - I'll have to close this down unless someone sends a PR with a code to solve it
