### ISSUE TITLE
iOS 7 Compatibility

### ISSUE THREAD

**Issue by Aymenworks** [icanzilb/SwiftSpinner#2]
Hi,
What can be done to use it on iOS 7 ?

**Comment by rinatkhanov** [comment]
CocoaPods 0.36 (required version for Swift pods) only [works](http://blog.cocoapods.org/Pod-Authors-Guide-to-CocoaPods-Frameworks/) on iOS 8 and newer. This is related to dynamic frameworks.

Thus, if you want to target for iOS 7, you need to include SwiftSpinner directly into your project. It compiles fine if you set project target to iOS 7, though I did not test it on the actual device.

**Comment by Aymenworks** [comment]
That's just the reason I'm here because I included SwiftSpinner.swift directly and it seems to crash without logs on iOS 7 Simulator Device. Can you test it again and tell me if you have the same problem, please ?

**Comment by icanzilb** [comment]
@Aymenworks this library uses blur and vibrancy effects - both APIs were added in iOS8, so you can't use it without modification in iOS7
