### ISSUE TITLE
Custom subtitle font

### ISSUE THREAD

**Issue by ndmeiri** [icanzilb/SwiftSpinner#22]
The ability to customize the subtitle font would be a nice addition to SwiftSpinner.

**Comment by gkye** [comment]
The ability to set background image of view and background image of spinner would be nice.
(wasnt too sure where to post feature request)

**Comment by icanzilb** [comment]
@ndmeiri not many people use the subtitle at all, so I wouldn't add a separate method to change the font - but you can access `subtitleLabel` on SwiftSpinner and change the font yourself :)

@gkye the spinner blurs the background of it's superview, e.g. what's currently on screen. In case you want to have a custom background while you're showing the spinner - your current view is where you should add it for the duration of the spinner
