### ISSUE TITLE
Prevent interaction while on display

### ISSUE THREAD

**Issue by kdomingo** [icanzilb/SwiftSpinner#25]
Hi there! I've just used your spinner today and found that the views below it still allow interaction while the spinner itself is on display.

**Comment by icanzilb** [comment]
it's on my todo for the next update already

**Comment by kdomingo** [comment]
ok cool.

**Comment by icanzilb** [comment]
I'll leave it open, just to make sure I don't forget :+1:

**Comment by icanzilb** [comment]
fixed and it will go to Cocoapods with the next pod version
