### ISSUE TITLE
Stops animating

### ISSUE THREAD

**Issue by batisa** [icanzilb/SwiftSpinner#27]
Ive tried to (in viewDidLoad and viewDidAppear) to start and stop animations in the main thread but cant get it to work.  I am new to swift and am looking for help.  I looked at the demo app in the zip file, but i dont want the spinning animation to only run for a select amount of time.  Any help is appreciated

i tried the following code in both view did appear and view did load:

```
    dispatch_async(dispatch_get_main_queue(), {
        SwiftSpinner.show("Processing data...", animated: true)
    })

    //parse some data here

    dispatch_async(dispatch_get_main_queue(),{
        SwiftSpinner.hide()
    })
```

**Comment by icanzilb** [comment]
Download the repo and check out the `ViewController.swift` file - it demonstrates how exactly you can do all of the things SwiftSpinner offers
