### ISSUE TITLE
Share Xcode scheme so SwiftSpinner works with Carthage

### ISSUE THREAD

**Issue by jpiche** [icanzilb/SwiftSpinner#28]
[Carthage](https://github.com/Carthage/Carthage) is a decentralized dependency manager that gives developers more control over how frameworks are integrated compared to CocoaPods, and is becoming increasingly popular. It uses `xcodebuild` to build dependancies instead of using a shared workspace, and the only requirement for frameworks is that there's a shared scheme so that the tool can discover and build it properly.

**Comment by icanzilb** [comment]
is there a step-by-step tutorial you can recommend?

**Comment by jpiche** [comment]
Here's a quick step-by-step from Apple docs: https://developer.apple.com/library/ios/recipes/xcode_help-scheme_editor/Articles/SchemeShare.html. Shared schemes are also used when automating testing via an Xcode build server.

**Comment by icanzilb** [comment]
thanks I'll have a look

**Comment by thbaja** [comment]
+1

**Comment by walsht** [comment]
+1

**Comment by dwoodgate** [comment]
I've forked, added Carthage support and submitted a pull req. 
#53

**Comment by icanzilb** [comment]
#53 is merged, thanks!
