### ISSUE TITLE
Cant compile and shows segmentation error

### ISSUE THREAD

**Issue by gvimlann** [icanzilb/SwiftSpinner#34]
Hi 
I m really interested to use your SwiftSpinner. I m currently on Xcode 7.1 beta. And I m getting the errors below .
![screen shot 2015-09-11 at 4 01 04 pm](https://cloud.githubusercontent.com/assets/9544447/9809860/7be5d252-589e-11e5-8c86-f803788ed970.png)
![screen shot 2015-09-11 at 4 00 46 pm](https://cloud.githubusercontent.com/assets/9544447/9809861/7c539ada-589e-11e5-8541-7a7e7ce73212.png)

Hope can solve this. Thank you

**Comment by icanzilb** [comment]
not sure what this is ... 7.1 is a very early beta so I didn't look into it
