### ISSUE TITLE
animateWithDuration

### ISSUE THREAD

**Issue by craigpearce5** [icanzilb/SwiftSpinner#44]
On upgrade to Xcode 7.1 and Swift 2 I am getting an error saying that `nil` is not compatible with `options:`.  Any recommendation on which option I should use?   

```
UIView.animateWithDuration(duration, delay: 0.0, usingSpringWithDamping: 0.4, initialSpringVelocity: 0.0, options: nil, animations:
```

**Comment by icanzilb** [comment]
You should check the iOS9 docs - instead of nil you need to put in []
