### ISSUE TITLE
title can't be showed

### ISSUE THREAD

**Issue by antzhi** [icanzilb/SwiftSpinner#48]
Hi!
  I use you Spinner in my iOS9.2 hybrid app to show uploadging in didRecieveJsNotification(). When I call show() method it show the circle without title and animate, before hiding it show the last title "100%" in a shot time

**Comment by MMasterson** [comment]
Does my PR help at all?

https://github.com/icanzilb/SwiftSpinner/pull/47

**Comment by icanzilb** [comment]
This should be okay in `0.9.0` - give it a try and re-open this if you still have a problem. If the bug is still there please include a piece of code so I can have a look what's going on.
