### ISSUE TITLE
Wont load on UIViewController but will on UINavigationController

### ISSUE THREAD

**Issue by l1k2j3h4g5** [icanzilb/SwiftSpinner#50]
I'm not sure why this is happening,. 

I tested this on a project with navigation controller. It worked, So I created a new project as I had another idea and put the code on. For some reason it wouldnt work. 

I check both projects and everything was the same apart from the class decleration. 

So I changed: 

`class ViewController: UIViewController {`

to 

`class ViewController: UINavigationController {`

and it worked. Any ideas how to get this to load in a blank view controller?

**Comment by icanzilb** [comment]
the demo app is a single-view-controller app

**Comment by l1k2j3h4g5** [comment]
I didnt use the demo project, when I tried initially I got this erorr: ld: warning: directory not found for option '-F/Users/testdbuser/Library/Developer/Xcode/DerivedData/SwiftSpinnerDemo-clhywecqtauylhghandpfnclumbl/Build/Products/Debug-iphonesimulator/Pods-SwiftSpinnerDemo'

**Comment by l1k2j3h4g5** [comment]
Also, why did you close this? saying something in a reply but not trying to figure out why my individual case is wrong is not good practice.
