### ISSUE TITLE
SwiftSpinner won't show when segueing from AppDelegate to ViewController

### ISSUE THREAD

**Issue by younanjo** [icanzilb/SwiftSpinner#54]
I made a simple project where I have two ViewControllers embedded in a Navigation controller. when i segue from first view controller to second view controller then SwiftSpinner shows up as expected. My second view controller with id "secondView" has a SwifSpinner in viewDidLoad().

Problem is when I try to segue to second view controller with id "secondView" directly from appDelegate. When segue is performed this way SwiftSpinner doesn't show up. Any ideas why or if there's a workaround? Below is my code:

```
import UIKit

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {

    var window: UIWindow?

    func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {

        let navController: UINavigationController = (self.window!.rootViewController as! UINavigationController)
        self.window = UIWindow(frame: UIScreen.mainScreen().bounds)
        let storyboard = UIStoryboard(name: "Main", bundle: nil)


        let initialViewController = storyboard.instantiateViewControllerWithIdentifier("secondView") as! SwitSpinnerViewController
        navController.pushViewController(initialViewController, animated: false)
        self.window?.rootViewController = navController

        return true
    }

}
```

```
import UIKit

import SwiftSpinner
class SwitSpinnerViewController: UIViewController {

    override func viewDidLoad() {
        super.viewDidLoad()

        SwiftSpinner.show("Testing")


    }
}

```

**Comment by younanjo** [comment]
this commit has the fix thanks to @MMasterson 

https://github.com/icanzilb/SwiftSpinner/commit/68e718bb8a675d0a92dba37ecfa57ec0e39c73fa

**Comment by MMasterson** [comment]
Anytime @younanjo, glad I could help!
