### ISSUE TITLE
Spinner not shown when called from AppDelegate

### ISSUE THREAD

**Issue by deepika1203** [icanzilb/SwiftSpinner#55]
I have no problem showing the Swift spinner from any function/view controller except AppDelegate. The problem comes only when I call SwiftSpinner.show("Loading...") from AppDelegate.  I have set breakpoints and checked. The show() function in SwiftSpinner.swift is getting called and executed. But the spinner is not shown on the window. I have also updated the code with this https://github.com/MMasterson/SwiftSpinner/commit/68e718bb8a675d0a92dba37ecfa57ec0e39c73fa . But still same problem. Anyone has any solution for this?

**Comment by deepika1203** [comment]
This problem could be solved with the following approach,

In AppDelegate,

```
class AppDelegate: UIResponder, UIApplicationDelegate {

    var window: UIWindow?

    func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {

        self.window = UIWindow(frame: UIScreen.mainScreen().bounds)

        self.appGlobals.setSpinnerWindow(self.window!)      //SwiftSpinner wont be displayed if the window is not set

        return true

    }
}
```

This is the AppGlobals class,

```
class AppGlobals: NSObject {
    var spinWindow: UIWindow!

    //Setting and getting AppDelegate window
    func setSpinnerWindow(win: UIWindow){
        spinWindow = win
    }

    func getSpinnerWindow() -> UIWindow {
        return spinWindow
    }
}
```

And in the SwiftSpinner.swift, we need to get the window like this, (in show() method)

```
public class func show(title: String, animated: Bool = true) -> SwiftSpinner {
    let spinner = SwiftSpinner.sharedInstance
    spinner.updateFrame()

    if spinner.superview == nil {
        //show the spinner
        spinner.alpha = 0.0
        AppGlobals().getSpinnerWindow().addSubview(spinner)   //Add the spinner to the app delegate window

        UIView.animateWithDuration(0.33, delay: 0.0, options: .CurveEaseOut, animations: {
            spinner.alpha = 1.0
        }, completion: nil)

        // Orientation change observer
        NSNotificationCenter.defaultCenter().addObserver(
            spinner,
            selector: "updateFrame",
            name: UIApplicationDidChangeStatusBarOrientationNotification,
            object: nil)
    }

    spinner.title = title
    spinner.animating = animated

    return spinner
}
```

**Comment by deepika1203** [comment]
If anyone has any other better approach for this problem, do share it..

**Comment by icanzilb** [comment]
interesting, I never thought about showing a spinner from the app delegate but it might be worth looking why is the window not available at that point, I'll leave this open so I remember to check when I'm updating the lib

**Comment by deepika1203** [comment]
Okay.. Even I am eager to know why the window is not available at that point..

**Comment by icanzilb** [comment]
yup - that's very awkward, even if you're trying to show the spinner from `viewDidLoad` of your first view controller `keyWindow` of your application is still `nil`. It seems like that's the intended behavior so I can't really do much about it. In `0.9.0` there's a new method called `useContainerView` which allows you to tell the spinner in which view it should appear - you can do your own window initialization and tell the spinner your window via the said method.
