### ISSUE TITLE
is it possible to resize the blur?

### ISSUE THREAD

**Issue by gadget00** [icanzilb/SwiftSpinner#56]
Im just wondering if instead of blurring the whole screen, would it be possible to set the parameters of the blur to maybe a smaller box in the middle or set it to a side, so we can use it to show loading without covering the whole screen(example: Zillow app loading message, a small block on the top)

thanks for your amazing code!

**Comment by kwstasna** [comment]
Agree!! 
This could be very nice update

**Comment by icanzilb** [comment]
It's theoretically possible if you'd animate the blur effect on the effect view, using a UIViewPropertyAnimator and stop the animation mid-way to a certain percentage ... but this solution will be iOS10 only and I'm not sure what the performance complications are
