### ISSUE TITLE
"No such Module?"

### ISSUE THREAD

**Issue by dbethala** [icanzilb/SwiftSpinner#6]
Getting a "No such Module" error next to "import SwiftSpinner" when trying to run the demo on the simulator. Sorry if this is a novice question. New to iOS development. Tried deleting the "DerivedData" folder, cleaning, and building, but no luck. Any suggestions? Thanks!

**Comment by icanzilb** [comment]
SwiftSpinner is accessible as a framework only when you import it via Cocoapods, did you check the readme?

**Comment by dbethala** [comment]
I did but just needed that clarification. Thank you!

**Comment by vasiliyb** [comment]
I am having a similar issue in XCode8.  Dragging the SwiftSpinner.swift into my workspace does not work, `import SwiftSpinner` throws.
Will try the Cocoapods instead...

*update: cocoapods work perfect
