### ISSUE TITLE
showWithDelay shows even after a hide()

### ISSUE THREAD

**Issue by perlguy99** [icanzilb/SwiftSpinner#60]
In the latest release, the hide() method does not seem to stop a showWithDelay from happening.

The following code

`SwiftSpinner.show("Authenticating...")`
`SwiftSpinner.showWithDelay(4.0, title: "Authenticating... Sorry, it's taking so long.", animated: true)`

Shows the "Authenticating..." spinner.  Then, 4 seconds later the "showWithDelay" spinner pops up, even if the "hide()" method has already been called.

**Comment by icanzilb** [comment]
I think this is more of a semantics issue - `hide()` technically should hide a spinner not `cancelAnyCurrentlyScheduledSpinners()`. That being said - maybe the best way is to bring back the broken behavior to be consistent with older versions.

**Comment by perlguy99** [comment]
Basically, I did roll back the showWithDelay to the previous version to keep the functionality that I had.

I may be using your (very cool) library/tool incorrectly...  What I want to do is display the spinner, then, if it has not been dismissed within 4 seconds, change the text to the "Sorry..." text.

Is there a better way to do this?

Anyway, I really appreciate you for putting this code out for others to use.  Thank you!

**Comment by icanzilb** [comment]
I thought more about this issue and the cleanest solution looks like adding a parameter that is by default `true` to match the previous behavior.
