### ISSUE TITLE
spinner loses custom font when calling "show" method next time

### ISSUE THREAD

**Issue by murad1981** [icanzilb/SwiftSpinner#62]
after setting a custom font using setTitleFont method, the custom font works only the first time the spinner is displayed, however, the spinner switches back to the default font next time I have the "show" method

**Comment by icanzilb** [comment]
I'l have a look at that when I have time to work on an update (or you can send a PR)

**Comment by murad1981** [comment]
you can fix it immediately at line 202 in SwiftSpinner.swift, just comment the line.

**Comment by nickdnk** [comment]
Hello guys

I fixed this in my iOS blur PR as well.

It'd be great if you can merge it soon and update pods, so I don't have to store my own version for every time I reload pods during development. :)

**Comment by nickdnk** [comment]
@icanzilb ? :)

**Comment by icanzilb** [comment]
merged
