### ISSUE TITLE
Bug fix involving UIFont and Xcode update

### ISSUE THREAD

**Issue by CrimsonKyle** [icanzilb/SwiftSpinner#65]
`var defaultTitleFont = UIFont(name: "HelveticaNeue", size: 22.0)!`

Needs to be changed to `.init` in order to build without errors.

`var defaultTitleFont = UIFont.init(name: "HelveticaNeue", size: 22.0)!`

**Comment by icanzilb** [comment]
what is the error here?

**Comment by CrimsonKyle** [comment]
`'(name: String, size: CGFloat) -> UIFont' is not convertible to '(name: String, size: CGFloat) -> UIFont?'`
(Only happens after update to Xcode 7.3)
- Unsure how widespread the issue is with the UIFont constructor but a co-worker was able replicate the error with this repository

**Comment by icanzilb** [comment]
My Xcode is Version 7.3.1 (7D1014) and I can't replicate your error. Can you run the demo app from this repo?
