### ISSUE TITLE
iOS 10 renders visible box around spinner

### ISSUE THREAD

**Issue by CrimsonKyle** [icanzilb/SwiftSpinner#69]
After upgrading to iOS 10 Beta 1 the library renders a box around the spinner for a second before starting the animation.

![ios_10_spinner_bug](https://cloud.githubusercontent.com/assets/16037523/16235548/e939bdce-379a-11e6-80ff-6ff476cd1434.png)

**Comment by icanzilb** [comment]
support for beta versions is not planned

**Comment by CrimsonKyle** [comment]
So support is planned after public release?

**Comment by icanzilb** [comment]
certainly no iOS 10 fixes can make it to `master` if the latest stable is iOS9, if you find the issue send me a PR and we can have an iOS10 branch, which people could use during the beta

**Comment by CrimsonKyle** [comment]
Sounds like a plan to me I personally try to head off any potential library issues with current apps in production while the OS is still in a beta release.

**Comment by icanzilb** [comment]
I've been losing a lot of time previous years in trying to support betas, so I'll pass. I created an 'iOS10' branch, your can PR there 👍

**Comment by fortmarek** [comment]
So now the iOS 10 is no longer in beta but I am still observing this bug. 

I am simply doing this:

``` swift
SwiftSpinner.show("Načítání")
```

**Comment by fortmarek** [comment]
Should be fixed now in this pull request: #77
