### ISSUE TITLE
Old text is still visible when showing a new text after hiding

### ISSUE THREAD

**Issue by ChaosCoder** [icanzilb/SwiftSpinner#7]
Showing text "A" (not animated), hiding it and then later showing text "B" let's you see the old text "A" during the fade in. This doesn't look good.

A solution is to fully remove the old text when you call hide.

**Comment by icanzilb** [comment]
I'll try to reproduce that and fix, thanks for reporting

**Comment by icanzilb** [comment]
fixed - the text is reset when you use hide()
