### ISSUE TITLE
Demo App looks great in simulator; barely readable on iPad Air 2

### ISSUE THREAD

**Issue by robcecil** [icanzilb/SwiftSpinner#71]
Just running the unmodified Demo app - it looks fine on the simulator - i can see the hurricane image blurred, rings are bright, text is bright.

On physical device - everything is very dark. Can't see the blurred hurricane. Barely read the text.

Brightness is turned up to ~ 75% on the device.

**Comment by icanzilb** [comment]
I don't have an iPad, but if you send a PR I'll definitely have a look at it :)

**Comment by robcecil** [comment]
Hi, sorry Marin. Should have followed through on that one. I think I remember finding that the visuals for the Spinner didn't work well with high contrast or some other accessibility setting on the device.
