### ISSUE TITLE
Text and circle color.

### ISSUE THREAD

**Issue by costantino78** [icanzilb/SwiftSpinner#73]
Hi, I want to know if the text and the circle can be set to a specific color rather than referring to the colors of the underlying view. In this specific case, I would like the text and the circle was white.

Best regards
Costantino

![textandcirclecolor](https://cloud.githubusercontent.com/assets/2123837/16921090/73c97eb8-4d10-11e6-9812-b363a5ad4d5e.png)

**Comment by icanzilb** [comment]
no there is no support for such a feature right now, if you want to work on one send a PR
