### ISSUE TITLE
iOS 10 Support

### ISSUE THREAD

**Issue by nevinjethmalani** [icanzilb/SwiftSpinner#74]
Love this spinner! 

I was testing it with iOS 10 and it is not working correctly. When do you think you will be able to add iOS 10 support? Please keep me posted as it is something we would love to leave in even when iOS 10 releases publicly.

**Comment by icanzilb** [comment]
people have sent PRs to the iOS10 and swift3 branches, you can give those a try and see if it works out for you

**Comment by icanzilb** [comment]
you can get the latest: https://github.com/icanzilb/SwiftSpinner/releases/tag/1.0.2
