### ISSUE TITLE
Visible square box on iOS 10

### ISSUE THREAD

**Issue by ghost** [icanzilb/SwiftSpinner#78]
As I see this issue was fixed in https://github.com/icanzilb/SwiftSpinner/pull/77 for Swift 3 version of Spinner(v. 1.0.1)

@icanzilb Can you create the same fix for 0.9.5 (Swift 2.3) and submit new version to cocoapods?

**Comment by icanzilb** [comment]
I'm not even sure if I can patch old versions of a Pod ... how would one do that?

**Comment by grinkevich-alex** [comment]
@icanzilb Just create new branch from 0.9.5 tag, make changes, change pod version/tag in podspec and run script to create new cocoapods version of Spinner. 
I hope this can help you https://guides.cocoapods.org/making/making-a-cocoapod.html

**Comment by sealz** [comment]
I just forked the repo and made the changes manually... https://github.com/sealz/SwiftSpinner it's on branch `swift2.3`

In your Podfile:

``` ruby
pod 'SwiftSpinner', :git => "git@github.com:sealz/SwiftSpinner.git", :branch => "swift2.3"
```

**Comment by icanzilb** [comment]
thanks
