### ISSUE TITLE
Swift 3 cocoapods release? 

### ISSUE THREAD

**Issue by razvandub** [icanzilb/SwiftSpinner#79]
Hi @icanzilb, 

Will 1.0.1 be pushed to cocoapods? 

Thanks.

**Comment by icanzilb** [comment]
CocoaPods still doesn't officially support Swift 3

**Comment by razvandub** [comment]
What exactly do you mean by that?

**Comment by icanzilb** [comment]
there's a problem when you try pushing a swift 3 pod to the pods trunk with the current release, I'm waiting for the PRs to fix this to merged towards the final 1.1.0

**Comment by razvandub** [comment]
ok thanks.

**Comment by TakanashiOuken** [comment]
Does SwiftSpinner support Swift 3 yet?

**Comment by icanzilb** [comment]
yes, if you pull from master

**Comment by icanzilb** [comment]
you can get the latest: https://github.com/icanzilb/SwiftSpinner/releases/tag/1.0.2

**Comment by TakanashiOuken** [comment]
Thx
But Xcode still ask me to convert :(
And the same error pops out
<img width="975" alt="screen shot 2016-09-20 at 4 27 46 pm" src="https://cloud.githubusercontent.com/assets/5293737/18662980/3b95fc76-7f4f-11e6-8b72-d4ed551d3375.png">

**Comment by icanzilb** [comment]
Does the DemoApp from the SwiftSpinner GitHub repo work for you?

**Comment by TakanashiOuken** [comment]
The Demo works. Didn't even as ask to convert.
But I created a clean Project but ask me to convert...

**Comment by iwheelbuy** [comment]
Everything started to work just now. I'm on latest beta cocoa pods

**Comment by icanzilb** [comment]
@TakanashiOuken then maybe have a look at your own project, maybe it still needs converting?

**Comment by TakanashiOuken** [comment]
It's a clean Project I created for testing....
I will make another one to try

**Comment by TakanashiOuken** [comment]
No good
If I install SwiftSpinner with pod "SwiftSpinner"
Xcode will ask me to convert it.
But seems like cocoapad installed 1.0.2 alright

**Comment by icanzilb** [comment]
maybe something like this? https://github.com/CocoaPods/CocoaPods/pull/5530

**Comment by TakanashiOuken** [comment]
@icanzilb 
You're right thanks so much
