### ISSUE TITLE
pod install fails on version 1.0.1

### ISSUE THREAD

**Issue by telcosolutions** [icanzilb/SwiftSpinner#80]
my podfile has

'SwiftSpinner', '= 1..0.1'
[!] Unable to satisfy the following requirements:
- `SwiftSpinner (= 1.0.1)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `SwiftSpinner (= 1.0.1)`.

Any idea what i'm doing wrong?

**Comment by icanzilb** [comment]
latest version on CocoaPods is this https://cocoapods.org/?q=swiftspinner
I'm waiting on CocoaPods to support pushing swift3 pods out of the box

**Comment by icanzilb** [comment]
you can get the latest: https://github.com/icanzilb/SwiftSpinner/releases/tag/1.0.2
