### ISSUE TITLE
swift 3 pod update?

### ISSUE THREAD

**Issue by RichardBoyder** [icanzilb/SwiftSpinner#82]
Hi there, any swift 3 pod update?

**Comment by icanzilb** [comment]
the latest version is swift 3

**Comment by RichardBoyder** [comment]
i did do a pod update, but still get this message:

SwiftSpinner will not be code signed because its settings don't specify a development team.
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

i removed the pod and reinstalled it but still same error. and also i try set “Use Legacy Swift Language Version”  to yes and still doesn't work?
