### ISSUE TITLE
SWIFT 3 pod update not coming through

### ISSUE THREAD

**Issue by RichardBoyder** [icanzilb/SwiftSpinner#84]
Hi there

I have updated pods but still the swift spinner pod hasnt updated yet.... Any news on this one?

**Comment by sneps85** [comment]
Same error here, getting 0.9.5 through Pods

**Comment by icanzilb** [comment]
sorry guys, after updated to Sierra I can't seem to push to CocoaPods 😢 waiting for a CocoaPods update

**Comment by RichardBoyder** [comment]
all good. Eagerly waiting for the update. Thanks for letting us know @icanzilb .

**Comment by icanzilb** [comment]
for the time being you can just load the specific tag you want like so: `pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :tag => '3.1.1'`

**Comment by RichardBoyder** [comment]
like so:

pod 'SwiftSpinner', :git => 'https://github.com/icanzilb/SwiftSpinner.git', :tag => '1.0.2'

I just tried that but still Xcode is shouting a at me... 135 issues :)

**Comment by icanzilb** [comment]
135 issues? that seems a bit disproportional for a single file of swift 😂 okay, I'm gonna try another time this week to push my pods up ... someone sent me a custom build I need to install, so I'll give it a try

**Comment by RichardBoyder** [comment]
haha yeah, I'm sorry i can't provide more info haha.

**Comment by RichardBoyder** [comment]
@icanzilb Any luck with pushing the pod up last week?

**Comment by RichardBoyder** [comment]
Hi guys, Has the POD been updated? Really need this to be working. pretty please?

**Comment by mjhassan** [comment]
Pod's current stable version is `1.1.1`, released 2016-10-20, and beta is `1.2.0.beta.1`, released 2016-10-28. Can you please fix and push your updated pod?
FYI, if you run your demo app in `Xcode 8.1` you will see the errors, 54 of them.

**Comment by icanzilb** [comment]
Guys, the current latest version is `1.1.0` - update your local pod repos. The demo app runs in Xcode 8.1 : https://cocoapods.org/?q=SwiftSpinner

If you see errors in the demo app - open a new issue or send a PR that fixes them along with instructions how to reproduce.
