### ISSUE TITLE
Show spin for task

### ISSUE THREAD

**Issue by rlaferla** [icanzilb/SwiftSpinner#85]
SwiftSpinner would be much more useful if it would display before executing some task and then hide when it was done.

```
func somemethod() {

 spinner.showWhile("Performing some task") {
   // do some stuff
  // hide
  }
}
```

Instead it has to wait for the method to return before displaying.  I tried an async dispatch but the spinner was slow to show and then displayed briefly at the end.

**Comment by icanzilb** [comment]
How's that different than calling hide() at the end of the task closure?
