### ISSUE TITLE
Adjust Text Brightness

### ISSUE THREAD

**Issue by jfield44** [icanzilb/SwiftSpinner#87]
Firstly, this is awesome. However I am using the spinner on a black background and the text appears a very light grey that is very difficult to read. Is it possible to make the text more pronounced?

**Comment by aamck** [comment]
You can access the labels directly to change their colours:

```
SwiftSpinner.sharedInstance.titleLabel
SwiftSpinner.sharedInstance.subtitleLabel
```

You can also access the colours of the inner and outer rings:

```
SwiftSpinner.sharedInstance.outerColor
SwiftSpinner.sharedInstance.innerColor
```

Edit: For some reason I got an email that this was a new issue, oh well hope it helps : >
