### ISSUE TITLE
EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by djneely** [icanzilb/SwiftSpinner#95]
I recently included this pod into our project. However, we're seeing a 'Thread 1: EXC_BAD_ACCESS (code=1, address=0x1cd)' when trying to show the spinner.

Any thoughts on what might be causing this?

![screen shot 2017-01-09 at 2 36 01 pm](https://cloud.githubusercontent.com/assets/981157/21780301/046e861a-d679-11e6-8612-e2278be58988.png)

**Comment by aamck** [comment]
If you comment out the line above setting the font and then clean the project, does it still crash?

**Comment by djneely** [comment]
Yes. I've commented that line out and it still crashes on the .show("")

**Comment by aamck** [comment]
Bad access suggests there is no instance of the SwiftSpinner to initialise I think. You could try removing the pod and re adding it to the project. Another alternative is to simple take the SwiftSpinner/SwiftSpinner.swift file and put it directly into the project.

**Comment by djneely** [comment]
Andrew,
Thank you for your timely responses. I did try to uninstall, clean, and re-install via the Pods but had not luck with that. 

However, I did grab the code and put it directly in my project as you suggested and that appears to be working. 

Again, thank you for the quick responses and getting us up and going with your product. And kudos to you on it. Very slick loader.

**Comment by aamck** [comment]
I didn't make it, I just contribute to 'give back' as I use it myself. Glad you got it working 👍
