### ISSUE TITLE
Blur animation is broken on iOS 10 (fix included)

### ISSUE THREAD

**Issue by nickdnk** [icanzilb/SwiftSpinner#99]
Hello

I really like this pod, but there's  a problem with the blur animation. It appears laggy because it's used incorrectly. You should *not* animate the opacity of a UIBlurEffect.

Here's what you need to fix. I tested this and it works:

In your init, you need to do:
```
blurView = UIVisualEffectView()
addSubview(blurView)
```

And not create the effect directly there. Just add a blank effect view without an effect.

Now, in your show method, you must change to animating the effect instead of the opacity. Given that you still want to animate the content in the middle, your result should look like this:

```
UIView.animate(withDuration: 0.33, delay: 0.0, options: .curveEaseOut, animations: {
                spinner.blurView.contentView.alpha = 1.0
                spinner.blurView.effect = UIBlurEffect.init(style: UIBlurEffectStyle.dark)
                
                }, completion: nil)
```

And in your hide:

```
UIView.animate(withDuration: 0.33, delay: 0.0, options: .curveEaseOut, animations: {
                spinner.blurView.effect = nil
                spinner.blurView.contentView.alpha = 0
                }, completion: {_ in
                    spinner.blurView.contentView.alpha = 1.0
                    spinner.removeFromSuperview()
                    spinner.titleLabel.font = spinner.defaultTitleFont 
                    spinner.titleLabel.text = nil

                    completion?()
            })
```
This is the way it's supposed to be used, and like this the blur animation will properly fade in and out, also on iOS 10.

I created a PR with the fix: https://github.com/icanzilb/SwiftSpinner/pull/100

**Comment by icanzilb** [comment]
has been merged, thanks!
